# escape=`
ARG baseImageTag
FROM inrule/inrule-server:${baseImageTag}
SHELL ["powershell", "-Command"]

ARG reposTag

LABEL	maintainer="jelster@inrule.com" `
		vendor="InRule Technology, Inc." `
        com.inrule.version="${reposTag}" `
        com.inrule.product="irCatalog" `
        com.inrule.product.flavor="AppServices"

EXPOSE 80:80
EXPOSE 443:443
EXPOSE 1433:1433

ENV ContainerDir=${ContainerDir:-"C:\inrule-catalog"} `
    inrule:repository:service:connectionString="Server=tcp:db,1433;User ID=sa;Password=asdf1234qwerty!;Initial Catalog=InRuleCatalog;" `
    reposTag=${reposTag} `
    irLogLevel="Warn"

RUN [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;`
    MD "$env:ContainerDir";cd "$env:ContainerDir"; `
    wget "https://github.com/InRule/AzureAppServices/releases/download/${env:reposTag}/InRule.Catalog.Service.zip" -OutFile "${env:ContainerDir}\irservice.zip"; `
    Expand-Archive -Path "${env:ContainerDir}\irservice.zip" -Destination "${env:ContainerDir}"; `
    Remove-Item "${env:ContainerDir}\irservice.zip"; `
    $acl = Get-Acl -AllCentralAccessPolicies -Path c:\inetpub\wwwroot; `
    (gci $env:ContainerDir -Recurse) | foreach { Set-Acl -Path $_.FullName -AclObject $acl -ErrorAction SilentlyContinue }; `
    Import-Module "WebAdministration"; `
    set-itemproperty -path 'IIS:\Sites\Default Web Site' -Name physicalPath -Value $env:ContainerDir;
    

WORKDIR C:\temp 
COPY *.ps1 .\
COPY configfragments.xml .\


SHELL ["C:\\LogMonitor\\LogMonitor.exe", "powershell.exe", ".\\Set-CatalogConfig.ps1 -wcfCfgFilePath .\\configfragments.xml -verbose;"]
# HACK to add new appSettings configuration until environment variable support is added
ENTRYPOINT C:\LogMonitor\ServiceMonitor.exe w3svc;
