# escape=`

FROM server/inrule-server:latest

LABEL	maintainer="jelster@inrule.com" `
		vendor="InRule Technology, Inc." `
        com.inrule.version="" `
        com.inrule.product="irCatalog"

ARG irCatalogDir
ARG ContainerDir

ENV CatalogDbHost="db" `
    CatalogUser="sa" `
    CatalogPassword="_" `
    CatalogDbName="InRuleCatalog" `
    ContainerDir=${ContainerDir:-"C:\inrule-catalog"}

ADD ${irCatalogDir:-irCatalog} ${ContainerDir}
COPY *.ps1 c:\temp\

RUN $acl = Get-Acl -AllCentralAccessPolicies -Path c:\inetpub\wwwroot;(gci $env:ContainerDir -Recurse) | foreach { Set-Acl -Path $_.FullName -AclObject $acl -ErrorAction SilentlyContinue }

RUN Import-Module "WebAdministration";`
    set-itemproperty -path 'IIS:\Sites\Default Web Site\' -Name physicalPath -Value $env:ContainerDir

#RUN Import-Module "WebAdministration";`
#    new-item 'IIS:\Sites\Default Web Site\InRuleCatalogService' -physicalPath C:\InRule\ -type Application -Verbose;

EXPOSE 80:80
EXPOSE 443:443
EXPOSE 1433:1433

WORKDIR C:\temp 

ENTRYPOINT .\Set-CatalogConfig.ps1 -catalogDbHostName $env:CatalogDbHost -catalogUserName $env:CatalogUser -catalogPassword $env:CatalogPassword -catalogInstallPath $env:ContainerDir -catalogDbName $env:CatalogDbName;

CMD .\Start.ps1;