# TODO: overhaul this!
parameters:
- name: inRuleReleaseTag
  type: string
  default: 'v5.8.1'

trigger:
- master

resources:
- repo: self

variables:
  ${{ if ne(variables['Build.SourceBranchName'], 'master')}}:
    imageTags: '$(Build.SourceBranchName)-$(Build.BuildId)'
  inRuleReleaseTag: ${{ parameters.inRuleReleaseTag }}

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Buildltsc2022
    displayName: Build LTSC2022
    pool:
      vmImage: 'windows-2022'
    steps:
    - task: PowerShell@2
      displayName: Run build script
      inputs:
        filePath: '$(Build.SourcesDirectory)\Developer Samples\WindowsContainers\Invoke-ContainerBuild.ps1'
        arguments: '-inRuleReleaseTag $(inRuleReleaseTag) -windowsServiceReleasesToUse ltsc2022'
        failOnStderr: true
        pwsh: true
        workingDirectory: '$(Build.SourcesDirectory)\Developer Samples\WindowsContainers'
    - task: PowerShell@2
      displayName: Populate variable with tag list from build output      
      inputs:
        targetType: 'inline'
        script: |
          write-host "##vso[task.setvariable variable=imageTagsToPush]$(gc "$env:Build_SourcesDirectory\Developer Samples\WindowsContainers\tags-built.txt")"
    - task: Docker@2 
      displayName: Push server image
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')) 
      inputs:
        containerRegistry: 'InRuleBuilds Docker Hub'
        command: 'push'
        repository: 'inrule/inrule-server'
        tags: 'ltsc2022'
    - task: Docker@2 
      displayName: Push catalog image
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')) 
      inputs:
        containerRegistry: 'InRuleBuilds Docker Hub'
        command: 'push'
        repository: 'inrule/inrule-catalog'
        tags: '$(inRuleReleaseTag)-ltsc2022'
    - task: Docker@2 
      displayName: Push catalog manager image
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')) 
      inputs:
        containerRegistry: 'InRuleBuilds Docker Hub'
        command: 'push'
        repository: 'inrule/inrule-catalog-manager'
        tags: '$(inRuleReleaseTag)-ltsc2022'
    - task: Docker@2 
      displayName: Push runtime image
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')) 
      inputs:
        containerRegistry: 'InRuleBuilds Docker Hub'
        command: 'push'
        repository: 'inrule/inrule-runtime'
        tags: '$(inRuleReleaseTag)-ltsc2022'

  - job: Buildltsc2019
    displayName: Build LTSC2019
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: PowerShell@2
      displayName: Run build script
      inputs:
        filePath: '$(Build.SourcesDirectory)\Developer Samples\WindowsContainers\Invoke-ContainerBuild.ps1'
        arguments: '-inRuleReleaseTag $(inRuleReleaseTag) -windowsServiceReleasesToUse ltsc2019'
        failOnStderr: true
        pwsh: true
        workingDirectory: '$(Build.SourcesDirectory)\Developer Samples\WindowsContainers'
    - task: PowerShell@2
      displayName: Populate variable with tag list from build output      
      inputs:
        targetType: 'inline'
        script: |
          write-host "##vso[task.setvariable variable=imageTagsToPush]$(gc "$env:Build_SourcesDirectory\Developer Samples\WindowsContainers\tags-built.txt")"
    - task: Docker@2 
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')) 
      inputs:
        containerRegistry: 'InRuleBuilds Docker Hub'
        command: 'push'
        repository: 'inrule/inrule-server'
        tags: 'ltsc2019'
    - task: Docker@2 
      displayName: Push catalog image
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')) 
      inputs:
        containerRegistry: 'InRuleBuilds Docker Hub'
        command: 'push'
        repository: 'inrule/inrule-catalog'
        tags: '$(inRuleReleaseTag)-ltsc2019'
    - task: Docker@2 
      displayName: Push catalog manager image
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')) 
      inputs:
        containerRegistry: 'InRuleBuilds Docker Hub'
        command: 'push'
        repository: 'inrule/inrule-catalog-manager'
        tags: '$(inRuleReleaseTag)-ltsc2019'
    - task: Docker@2 
      displayName: Push runtime image
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')) 
      inputs:
        containerRegistry: 'InRuleBuilds Docker Hub'
        command: 'push'
        repository: 'inrule/inrule-runtime'
        tags: '$(inRuleReleaseTag)-ltsc2019'
