# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
- imageTags: null # add items to the array to use as tag suffix, e.g., 'preview' becomes v5.5.1-ltsc2019-preview
- inRuleReleaseTag: v5.5.1

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          .\Invoke-ContainerBuild.ps1 -inRuleReleaseTag $(inRuleReleaseTag) -imageTags $(imageTags) | docker push
        failOnStderr: true
        workingDirectory: '$(Build.SourcesDirectory)\Developer Samples\WindowsContainers'