version: '2.4'

services: 
    rex:
        depends_on:
            - cat
        image: inrule/inrule-runtime:latest
        ports:
            - "80"
    cat:
        depends_on:
            - db
        image: inrule/inrule-catalog:latest
        ports:
            - "80"
    webcatman:
        depends_on:
            - cat
        ports:
            - "80"
        image: inrule/inrule-catalog-manager:latest
    db:
        image: inrule/inrule-catalog-db:latest
        ports:
            - "1433"
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_PID=Developer
