# escape=`

FROM inrule/inrule-server:latest AS build-stage
ARG reposTag
WORKDIR C:\assets\
ADD https://github.com/InRule/AzureAppServices/releases/download/${reposTag}/InRule.Catalog.Manager.Web.zip c:\assets

RUN Expand-Archive -Path InRule.Catalog.Manager.Web.zip -Destination c:\assets
RUN Remove-Item .\InRule.Catalog.Manager.Web.zip
FROM inrule/inrule-server:latest as deploy

EXPOSE 80:80
EXPOSE 443:443

LABEL	maintainer="jelster@inrule.com" `
		vendor="InRule Technology, Inc." `
        com.inrule.version="${reposTag}" `
        com.inrule.product="Web Catalog Manager"`
        com.inrule.product.flavor="AppServices"
        
ENV catManDir=c:\inrule-catalog-manager
ENV InRule:Catalog:Uri=http://cat/Service.svc

COPY --from=build-stage c:\assets ${catManDir}\
WORKDIR c:\temp
COPY *.ps1 .\

RUN $acl = Get-Acl -AllCentralAccessPolicies -Path c:\inetpub\wwwroot;(gci ${catManDir} -Recurse) | foreach { Set-Acl -Path $_.FullName -AclObject $acl -ErrorAction SilentlyContinue }

RUN Import-Module "WebAdministration";set-itemproperty -path 'IIS:\Sites\Default Web Site' -Name physicalPath -Value $env:catManDir

# HACK to disable TLS in WCF bindings until SSL is supported
RUN (Get-Content $env:catManDir\web.config) | foreach { $_.Replace('Transport', 'None') } | set-content "$env:catManDir\web.config" -force
ENTRYPOINT .\Set-CatalogManagerConfig.ps1 -verbose;
CMD .\Start.ps1