# escape=`

FROM mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2019

LABEL	maintainer="jelster@inrule.com" `
		vendor="InRule Technology, Inc." `
        com.inrule.version=""

SHELL ["powershell", "-Command"]

ADD . c:\temp\
WORKDIR c:\temp\
RUN .\InRuleServerDSC.ps1 -Wait;Remove-Item c:\temp\*.* -recurse -force;
RUN Import-module WebAdministration; `
    New-WebBinding -Name 'Default Web Site' -IP "*" -Port 443 -Protocol 'https'; ` 
    New-EventLog -LogName InRule -Source "InRule.Repository","InRule.Repository.Service","InRule.Runtime","InRule.Runtime.Service","InRule.Authoring.irAuthor","InRule.Admin.CatalogManager";