# escape=`

FROM microsoft/dotnet-framework:4.7.1-windowsservercore-1709

LABEL	maintainer="jelster@inrule.com" `
		vendor="InRule Technology, Inc." `
        com.inrule.version=""

SHELL ["powershell", "-Command"]

ADD . c:\temp\
WORKDIR c:\temp\
RUN .\InRuleServerDSC.ps1 -Wait;
RUN New-EventLog -LogName InRule -Source "InRule.Repository","InRule.Repository.Service","InRule.Runtime","InRule.Runtime.Service","InRule.Authoring.irAuthor","InRule.Admin.CatalogManager"