# escape=`

FROM mcr.microsoft.com/powershell:nanoserver-1903 as builder

SHELL [ "pwsh.exe", "-Command" ]
ARG irVersion=v5.5.0

ENV irVersion=${irVersion}
# e.g., "Server=(local);Database=InRuleCatalog;Trusted_Connection=True;"
RUN md c:\inrule; `
    cd c:\inrule; `
    invoke-webrequest https://github.com/InRule/AzureAppServices/releases/download/${env:irVersion}/InRule.Catalog.Service.Database.zip -outfile dbtool.zip; `
    expand-archive dbtool.zip -destination c:\inrule; `
    remove-item dbtool.zip

#RUN chmod 775 /inrule/InRule.Catalog.Service.Database.exe

FROM microsoft/mssql-server-windows-express:latest as runtime
SHELL [ "powershell" ]

RUN start-sleep 30;sqlcmd -S localhost -Q 'CREATE DATABASE InRuleCatalog'
COPY --from=builder c:\inrule\ c:\inrule

ENV ConnectionString="Server=(local);Database=InRuleCatalog;Trusted_Connection=True;"

RUN c:\inrule\InRule.Catalog.Service.Database.exe