# escape=`

FROM inrule/inrule-server:ltsc2019
SHELL ["powershell", "-Command"]

ARG reposTag

LABEL	maintainer="jelster@inrule.com" `
		vendor="InRule Technology, Inc." `
        com.inrule.version="${reposTag}" `
        com.inrule.product="irServer"`
        com.inrule.product.flavor="AppServices"

EXPOSE 80:80
EXPOSE 443:443

ENV inrule:runtime:service:catalog:catalogServiceUri="http://cat/Service.svc" `
inrule:runtime:service:catalog:userName="" `
inrule:runtime:service:catalog:password="" `
ContainerDir="C:\inrule-runtime" `
reposTag=${reposTag} `
irLogLevel="Warn"

RUN MD "$env:ContainerDir";cd "$env:ContainerDir"; `
    wget "https://github.com/InRule/AzureAppServices/releases/download/${env:reposTag}/InRule.Runtime.Service.zip" -OutFile "${env:ContainerDir}\irservice.zip"; `
    Expand-Archive -Path "${env:ContainerDir}\irservice.zip" -Destination "${env:ContainerDir}"; `
    Remove-Item "${env:ContainerDir}\irservice.zip";

RUN $acl = Get-Acl -AllCentralAccessPolicies -Path c:\inetpub\wwwroot; `
    (gci $env:ContainerDir -Recurse) | foreach { Set-Acl -Path $_.FullName -AclObject $acl -ErrorAction SilentlyContinue }

RUN Import-Module "WebAdministration"; `
 set-itemproperty -path 'IIS:\Sites\Default Web Site' -Name physicalPath -Value $env:ContainerDir; `
# HACK to disable TLS in WCF bindings until SSL is supported
(Get-Content $env:ContainerDir\web.config) | foreach { $_.Replace('Transport', 'None') } | set-content "$env:ContainerDir\web.config" -force;

WORKDIR C:\temp
COPY *.ps1 .\

# HACK to add new appSettings configuration until environment variable support is added
ENTRYPOINT .\Set-RuntimeConfig.ps1 -verbose;
CMD .\Start.ps1