# escape=`

FROM inrule/inrule-server:latest AS build-stage

ARG reposTag=v5.1.1
WORKDIR C:\assets\
ADD https://github.com/InRule/AzureAppServices/releases/download/${reposTag}/InRule.Runtime.Service.zip c:\assets
RUN Expand-Archive -Path InRule.Runtime.Service.zip -Destination c:\assets
RUN Remove-Item .\InRule.Runtime.Service.zip, .\InRuleLicense.xml

FROM inrule/inrule-server:latest as deploy

LABEL	maintainer="jelster@inrule.com" `
		vendor="InRule Technology, Inc." `
        com.inrule.version="${reposTag}" `
        com.inrule.product="irServer"`
        com.inrule.product.flavor="AppServices"

EXPOSE 80:80
EXPOSE 443:443

ENV inrule:runtime:service:catalog:catalogServiceUri="http://cat/Service.svc" `
inrule:runtime:service:catalog:userName="" `
inrule:runtime:service:catalog:password="" `
ContainerDir="C:\inrule-runtime"

COPY --from=build-stage c:\assets ${ContainerDir}\
WORKDIR C:\temp
COPY *.ps1 .\

RUN $acl = Get-Acl -AllCentralAccessPolicies -Path c:\inetpub\wwwroot;(gci $env:ContainerDir -Recurse) | foreach { Set-Acl -Path $_.FullName -AclObject $acl -ErrorAction SilentlyContinue }

RUN Import-Module "WebAdministration";set-itemproperty -path 'IIS:\Sites\Default Web Site' -Name physicalPath -Value $env:ContainerDir

# HACK to disable TLS in WCF bindings until SSL is supported

RUN (Get-Content $env:ContainerDir\web.config) | foreach { $_.Replace('Transport', 'None') } | set-content "$env:ContainerDir\web.config" -force

# HACK to add new appSettings configuration until environment variable support is added
ENTRYPOINT .\Set-RuntimeConfig.ps1 -verbose;
CMD .\Start.ps1